version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2022
build_script:
- ps: >-
    cmake -S . -B cmake-build -G"Visual Studio 17 2022" -DFETCH_SDL=ON -DAUTO_FORMAT=OFF
    cmake --build cmake-build
    cd cmake-build
    ctest -j8 -C Debug -T test --output-on-failure 
