version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2022
build_script:
- ps: >-
    cmake -S . -B cmake-build -G"Visual Studio 17 2022"

    cmake --build cmake-build