row = 12
col = 12

[ content ]

wooden_wall_up = [0, 1]
wooden_wall_right = [1, 1]
wooden_wall_down = [2, 1]
wooden_wall_left = [3, 1]
wooden_wall_up_right = [4, 1]
wooden_wall_up_down = [5, 1]
wooden_wall_up_left = [6, 1]
wooden_wall_right_down = [7, 1]
wooden_wall_left_right = [8, 1]
wooden_wall_left_down = [9, 1]
wooden_wall_open = [10, 1]
wooden_wall_close = [11, 1]

brick_wall_up = [0, 1]
brick_wall_right = [1, 1]
brick_wall_down = [2, 1]
brick_wall_left = [3, 1]
brick_wall_up_right = [4, 1]
brick_wall_up_down = [5, 1]
brick_wall_up_left = [6, 1]
brick_wall_right_down = [7, 1]
brick_wall_left_right = [8, 1]
brick_wall_left_down = [9, 1]
brick_wall_open = [10, 1]
brick_wall_close = [11, 1]

table_up = [0, 3]
table_right = [1, 3]
table_down = [2, 3]
table_left = [3, 3]
table_up_right = [4, 3]
table_up_down = [5, 3]
table_up_left = [6, 3]
table_right_down = [7, 3]
table_left_right = [8, 3]
table_left_down = [9, 3]
table_open = [10, 3]
table_close = [11, 3]

chair_up = [0, 7]
chair_right = [1, 7]
chair_down = [2, 7]

bed_down = [3, 7]
bed_right = [4, 7]

glass_door_vertical_close_top = [0, 5]
glass_door_vertical_close_bottom = [0, 6]
glass_door_vertical_open_top = [7, 5]
glass_door_vertical_open_bottom = [7, 6]
glass_door_horizontal_close = [1, 5]
glass_door_horizontal_open = [1, 6]

wooden_door_vertical_close_top = [2, 5]
wooden_door_vertical_close_bottom = [2, 6]
wooden_door_vertical_open_top = [6, 5]
wooden_door_vertical_open_bottom = [6, 6]
wooden_door_horizontal_close = [3, 5]
wooden_door_horizontal_open = [3, 6]

glass_wall_horizontal = [4, 6]
glass_wall_vertical_top = [5, 5]
glass_wall_vertical_bottom = [5, 6]

stone_sword = [0, 8]
stone_pickaxe = [1, 8]

tree_branch = [0, 9]
big_stone = [1, 9]
round_stone = [2, 9]
sharp_stone = [3, 9]
wooden_stake = [4, 9]

grass1 = [0, 10]
grass2 = [0, 11]
shore_corner = [1, 10]
shore_vertical = [1, 11]
shore_horizontal = [2, 10]
water1 = [2, 11]
water2 = [3, 11]

hint_arrow = [4, 10]