name: build-under-ubuntu
run-name: build-ubuntu
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: sudo apt install libsdl2{,-image,-mixer,-ttf}-dev
      - run: cmake -S . -B cmake-build
      - run: cmake --build cmake-build
