name: build-under-ubuntu
run-name: build-ubuntu
on: [push, pull_request]
jobs:
  build-project-under-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: sudo apt update
      - run: sudo apt install libsdl2{,-image,-mixer,-ttf}-dev clang
      - run: cmake -S . -B cmake-build -DCMAKE_CXX_COMPILER=clang++
      - run: cmake --build cmake-build
